language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
  - '10'
before_install: yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - npm prune
script:
  - mkdir -p reports
  - yarn add jest
  - yarn run test -- --coverage
  - yarn run lint --silent -- -t json | tee reports/lint-results.json
  - yarn run danger
after_success:
  - greenkeeper-lockfile-upload
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
